name: "Dickson Li"
title: "Dickson Li"
url: "https://dicksonli.com"
baseurl: "/index"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: ""
footer_text: "Â© 2020 All rights reserved."

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "index"
 - name: "Posts"
   link: "posts"
 - name: "Contact"
   link: "contact"
 - name: "Reading List"
   link: "reading_list"
